# Generated by Django 5.2.5 on 2025-08-11 23:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='usd_exchange_rate',
            field=models.DecimalField(decimal_places=6, help_text='Current rate to convert to USD', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
    ]
