# Generated by Django 5.2.6 on 2025-09-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_currency_usd_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user_tier',
            field=models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP'), ('vip_premium', 'VIP Premium')], max_length=15),
        ),
    ]
