version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://vipride:password@db:5432/vipride_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=dev-docker-secret-key-change-in-production
    depends_on:
      - db
      - redis
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=vipride_db
      - POSTGRES_USER=vipride
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A vip_ride_platform worker -l info
    volumes:
      - .:/code
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://vipride:password@db:5432/vipride_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=dev-docker-secret-key-change-in-production
    depends_on:
      - db
      - redis

  flower:
    build: .
    command: celery -A vip_ride_platform flower
    ports:
      - "5555:5555"
    environment:
      - DEBUG=True
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

volumes:
  postgres_data:
  static_volume:
  media_volume:
