# Generated by Django 5.2.5 on 2025-08-11 23:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_alter_pricingzone_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalcode',
            name='discount_value',
            field=models.DecimalField(
                decimal_places=2,
                help_text='Percentage (0-100) or fixed amount',
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal('0'))
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name='pricingzone',
            constraint=models.CheckConstraint(
                check=models.Q(('min_latitude__lt', models.F('max_latitude'))),
                name='pricing_zone_lat_bounds_check',
            ),
        ),
        migrations.AddConstraint(
            model_name='pricingzone',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('min_longitude__lt', models.F('max_longitude'))
                ),
                name='pricing_zone_lng_bounds_check',
            ),
        ),
    ]
