apiVersion: v1
kind: ConfigMap
metadata:
  name: vip-ride-config
  namespace: vip-ride-platform
data:
  DEBUG: "false"
  USE_POSTGRES: "true"
  DB_HOST: postgres-service
  DB_PORT: "5432"
  REDIS_URL: "redis://redis-service:6379/0"
