# Generated by Django 5.2.5 on 2025-08-12 01:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPartnership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel_name', models.CharField(max_length=160)),
                ('contact_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('rooms_count', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_type', models.CharField(choices=[('contact', 'Contact'), ('driver_private', 'Private Driver'), ('driver_fleet', 'Fleet Company'), ('vehicle_owner', 'Vehicle Owner'), ('hotel_partner', 'Hotel Partner')], max_length=40)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('message', models.TextField(blank=True)),
                ('consent', models.BooleanField(default=False, help_text='I agree to be contacted.')),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('page', models.CharField(blank=True, max_length=160)),
                ('language', models.CharField(default='en', max_length=8)),
            ],
            options={
                'indexes': [models.Index(fields=['lead_type', 'created_at'], name='marketing_l_lead_ty_82954d_idx'), models.Index(fields=['email'], name='marketing_l_email_c4b755_idx')],
            },
        ),
    ]
