# Generated by Django 5.2.5 on 2025-08-12 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('ar', 'Arabic')], default='en', max_length=8),
        ),
    ]
