# Generated by Django 5.2.5 on 2025-08-06 13:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('budget', 'Budget Hotel'), ('standard', 'Standard Hotel'), ('luxury', 'Luxury Hotel'), ('resort', 'Resort'), ('boutique', 'Boutique Hotel'), ('business', 'Business Hotel')], default='standard', max_length=10)),
                ('partnership_tier', models.CharField(choices=[('bronze', 'Bronze Partner'), ('silver', 'Silver Partner'), ('gold', 'Gold Partner'), ('platinum', 'Platinum Partner'), ('exclusive', 'Exclusive Partner')], default='bronze', max_length=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Commission rate percentage (0-50%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('preferred_partner', models.BooleanField(default=False, help_text='Shows in premium listings for Premium/VIP users')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('star_rating', models.PositiveIntegerField(help_text='Hotel star rating (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('total_rooms', models.PositiveIntegerField()),
                ('check_in_time', models.TimeField(default='14:00')),
                ('check_out_time', models.TimeField(default='12:00')),
                ('amenities', models.JSONField(default=list, help_text='List of hotel amenities')),
                ('cancellation_policy', models.TextField()),
                ('child_policy', models.TextField(blank=True)),
                ('pet_policy', models.TextField(blank=True)),
                ('smoking_policy', models.TextField(blank=True)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=7.5, help_text='Tax rate percentage', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('partnership_start_date', models.DateField()),
                ('partnership_end_date', models.DateField(blank=True, null=True)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('response_time_hours', models.PositiveIntegerField(default=24, help_text='Average response time for booking confirmations')),
                ('premium_discount_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Special discount for Premium users (%)', max_digits=5)),
                ('vip_discount_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Special discount for VIP users (%)', max_digits=5)),
                ('data_processing_agreement_signed', models.BooleanField(default=False, help_text='Has signed data processing agreement')),
                ('data_retention_period_days', models.PositiveIntegerField(default=365, help_text='Days to retain customer data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hotel_partners',
                'indexes': [models.Index(fields=['city', 'state'], name='hotel_partn_city_5e632c_idx'), models.Index(fields=['category'], name='hotel_partn_categor_7a295f_idx'), models.Index(fields=['partnership_tier'], name='hotel_partn_partner_85e74b_idx'), models.Index(fields=['preferred_partner'], name='hotel_partn_preferr_7324bf_idx'), models.Index(fields=['is_active'], name='hotel_partn_is_acti_c5b233_idx'), models.Index(fields=['average_rating'], name='hotel_partn_average_16acd2_idx'), models.Index(fields=['star_rating'], name='hotel_partn_star_ra_b8dc48_idx')],
            },
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('standard', 'Standard Room'), ('deluxe', 'Deluxe Room'), ('suite', 'Suite'), ('executive', 'Executive Room'), ('presidential', 'Presidential Suite'), ('family', 'Family Room')], default='standard', max_length=15)),
                ('room_number', models.CharField(blank=True, max_length=10)),
                ('floor', models.PositiveIntegerField(blank=True, null=True)),
                ('max_adults', models.PositiveIntegerField(default=2)),
                ('max_children', models.PositiveIntegerField(default=0)),
                ('max_occupancy', models.PositiveIntegerField(default=2)),
                ('size_sqm', models.PositiveIntegerField(blank=True, help_text='Room size in square meters', null=True)),
                ('bed_type', models.CharField(default='Queen Bed', help_text='e.g., King Bed, Twin Beds, etc.', max_length=50)),
                ('room_amenities', models.JSONField(default=list, help_text='Room-specific amenities')),
                ('base_price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('weekend_price_multiplier', models.DecimalField(decimal_places=2, default=1.2, help_text='Weekend price multiplier (1.20 = 20% increase)', max_digits=3)),
                ('holiday_price_multiplier', models.DecimalField(decimal_places=2, default=1.5, help_text='Holiday price multiplier', max_digits=3)),
                ('is_available', models.BooleanField(default=True)),
                ('maintenance_start', models.DateTimeField(blank=True, null=True)),
                ('maintenance_end', models.DateTimeField(blank=True, null=True)),
                ('images', models.JSONField(default=list, help_text='List of room image URLs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotelpartner')),
            ],
            options={
                'db_table': 'hotel_rooms',
            },
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('actual_check_in', models.DateTimeField(blank=True, null=True)),
                ('actual_check_out', models.DateTimeField(blank=True, null=True)),
                ('primary_guest_name', models.CharField(max_length=200)),
                ('primary_guest_phone', models.CharField(max_length=20)),
                ('primary_guest_email', models.EmailField(max_length=254)),
                ('number_of_adults', models.PositiveIntegerField(default=1)),
                ('number_of_children', models.PositiveIntegerField(default=0)),
                ('guest_details', models.JSONField(default=dict, help_text='Additional guest information')),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=15)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('room_rate_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_nights', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_tier_discount', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount based on Premium/VIP status', max_digits=10)),
                ('promotional_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hotel_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('special_requests', models.TextField(blank=True)),
                ('early_check_in_requested', models.BooleanField(default=False)),
                ('late_check_out_requested', models.BooleanField(default=False)),
                ('airport_pickup_requested', models.BooleanField(default=False)),
                ('hotel_dropoff_requested', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rating', models.PositiveIntegerField(blank=True, help_text='Customer rating (1-5 stars)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('personal_data_consent', models.BooleanField(default=False, help_text='Guest consent for data processing')),
                ('marketing_consent', models.BooleanField(default=False, help_text='Consent for marketing communications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_bookings', to=settings.AUTH_USER_MODEL)),
                ('ride_booking', models.ForeignKey(blank=True, help_text='Associated ride for hotel transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_transfer_bookings', to='rides.ride')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_bookings', to='hotels.hotelpartner')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_bookings', to='hotels.hotelroom')),
            ],
            options={
                'db_table': 'hotel_bookings',
            },
        ),
        migrations.AddIndex(
            model_name='hotelroom',
            index=models.Index(fields=['hotel'], name='hotel_rooms_hotel_i_3e823c_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelroom',
            index=models.Index(fields=['room_type'], name='hotel_rooms_room_ty_23f746_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelroom',
            index=models.Index(fields=['is_available'], name='hotel_rooms_is_avai_b910de_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelroom',
            index=models.Index(fields=['base_price_per_night'], name='hotel_rooms_base_pr_8398b8_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelbooking',
            index=models.Index(fields=['customer'], name='hotel_booki_custome_2296f1_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelbooking',
            index=models.Index(fields=['hotel'], name='hotel_booki_hotel_i_d8c505_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelbooking',
            index=models.Index(fields=['room'], name='hotel_booki_room_id_75cecf_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelbooking',
            index=models.Index(fields=['status'], name='hotel_booki_status_ace1fc_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelbooking',
            index=models.Index(fields=['check_in_date'], name='hotel_booki_check_i_69d8e1_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelbooking',
            index=models.Index(fields=['check_out_date'], name='hotel_booki_check_o_216a68_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelbooking',
            index=models.Index(fields=['booked_at'], name='hotel_booki_booked__8a23b8_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelbooking',
            index=models.Index(fields=['ride_booking'], name='hotel_booki_ride_bo_eaa62e_idx'),
        ),
    ]
