# Generated by Django 5.2.5 on 2025-08-06 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('fleet_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='fleet_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='fleet_management.fleetcompany'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mfatoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='users_phone_n_a3b1c5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type'], name='users_user_ty_578f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tier'], name='users_tier_8aada5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_created_6541e9_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['license_number'], name='drivers_license_29348f_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['status'], name='drivers_status_fa78f3_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['category'], name='drivers_categor_71dd9d_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['subscription_tier'], name='drivers_subscri_e44f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['is_online', 'is_available'], name='drivers_is_onli_7cc088_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['fleet_company'], name='drivers_fleet_c_d4872a_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['average_rating'], name='drivers_average_f8b23c_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['created_at'], name='drivers_created_89688b_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['user', 'created_at'], name='login_attem_user_id_18b2e6_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['email', 'created_at'], name='login_attem_email_61a0cd_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['ip_address', 'created_at'], name='login_attem_ip_addr_f68fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['success', 'created_at'], name='login_attem_success_965250_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['is_suspicious'], name='login_attem_is_susp_909df1_idx'),
        ),
        migrations.AddIndex(
            model_name='mfatoken',
            index=models.Index(fields=['user', 'is_active'], name='mfa_tokens_user_id_a15fbf_idx'),
        ),
        migrations.AddIndex(
            model_name='mfatoken',
            index=models.Index(fields=['token_type'], name='mfa_tokens_token_t_15e920_idx'),
        ),
        migrations.AddIndex(
            model_name='mfatoken',
            index=models.Index(fields=['is_primary'], name='mfa_tokens_is_prim_2ba5de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mfatoken',
            unique_together={('user', 'token_type')},
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['user', 'created_at'], name='security_ev_user_id_70c595_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'severity'], name='security_ev_event_t_4d4c77_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['is_resolved'], name='security_ev_is_reso_f0a99f_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['created_at'], name='security_ev_created_510c16_idx'),
        ),
        migrations.AddIndex(
            model_name='trusteddevice',
            index=models.Index(fields=['user', 'is_active'], name='trusted_dev_user_id_02eb40_idx'),
        ),
        migrations.AddIndex(
            model_name='trusteddevice',
            index=models.Index(fields=['device_fingerprint'], name='trusted_dev_device__9a8b0f_idx'),
        ),
        migrations.AddIndex(
            model_name='trusteddevice',
            index=models.Index(fields=['last_used_at'], name='trusted_dev_last_us_2831f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trusteddevice',
            unique_together={('user', 'device_fingerprint')},
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='user_sessio_user_id_bb1b83_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_id'], name='user_sessio_session_e62ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['expires_at'], name='user_sessio_expires_66ae96_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['ip_address'], name='user_sessio_ip_addr_0626e4_idx'),
        ),
    ]
