# Generated by Django 5.2.5 on 2025-08-06 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('fleet_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='fleet_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='fleet_management.fleetcompany'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='users_phone_n_a3b1c5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type'], name='users_user_ty_578f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tier'], name='users_tier_8aada5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_created_6541e9_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['license_number'], name='drivers_license_29348f_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['status'], name='drivers_status_fa78f3_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['category'], name='drivers_categor_71dd9d_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['subscription_tier'], name='drivers_subscri_e44f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['is_online', 'is_available'], name='drivers_is_onli_7cc088_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['fleet_company'], name='drivers_fleet_c_d4872a_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['average_rating'], name='drivers_average_f8b23c_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['created_at'], name='drivers_created_89688b_idx'),
        ),
    ]
