# Generated by Django 5.2.6 on 2025-09-09 21:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumDigitalCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_number', models.CharField(help_text='16-digit card number displayed to user', max_length=16, unique=True)),
                ('verification_code', models.CharField(help_text='8-digit verification code for activation', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Must be exactly 8 digits', regex='^\\d{8}$')])),
                ('tier', models.CharField(choices=[('premium', 'Premium'), ('vip', 'VIP')], default='premium', max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available for Purchase'), ('sold', 'Sold but Not Activated'), ('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='available', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=99.99, max_digits=10)),
                ('validity_months', models.PositiveIntegerField(default=12, help_text='Card validity in months')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('purchase_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('activation_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premium_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'premium_digital_cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PremiumCardTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.premiumdigitalcard')),
            ],
            options={
                'db_table': 'premium_card_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='premiumdigitalcard',
            index=models.Index(fields=['card_number'], name='premium_dig_card_nu_3013ba_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumdigitalcard',
            index=models.Index(fields=['verification_code'], name='premium_dig_verific_de2db6_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumdigitalcard',
            index=models.Index(fields=['owner', 'status'], name='premium_dig_owner_i_c4e8bd_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumdigitalcard',
            index=models.Index(fields=['status'], name='premium_dig_status_3dc782_idx'),
        ),
    ]
