# Generated by Django 5.2.6 on 2025-09-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_premiumdigitalcard_premiumcardtransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumdigitalcard',
            name='tier',
            field=models.CharField(choices=[('vip', 'VIP'), ('vip_premium', 'VIP Premium')], default='vip', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP'), ('vip_premium', 'VIP Premium')], default='normal', max_length=15),
        ),
    ]
