# Generated by Django 5.2.6 on 2025-09-11 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_create_vip_card_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardactivationhistory',
            options={'ordering': ['-activation_date']},
        ),
        migrations.AlterModelOptions(
            name='cardbatchgeneration',
            options={'ordering': ['-generated_date']},
        ),
        migrations.RenameField(
            model_name='cardactivationhistory',
            old_name='attempt_time',
            new_name='activation_date',
        ),
        migrations.RenameField(
            model_name='cardactivationhistory',
            old_name='ip_address',
            new_name='client_ip',
        ),
        migrations.RenameField(
            model_name='cardbatchgeneration',
            old_name='generated_at',
            new_name='generated_date',
        ),
        migrations.RemoveField(
            model_name='cardactivationhistory',
            name='activation_code_attempted',
        ),
        migrations.RemoveField(
            model_name='cardactivationhistory',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='cardactivationhistory',
            name='serial_number_attempted',
        ),
        migrations.RemoveField(
            model_name='cardactivationhistory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cardactivationhistory',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='cardbatchgeneration',
            name='purpose',
        ),
        migrations.AddField(
            model_name='cardactivationhistory',
            name='new_tier',
            field=models.CharField(default='regular', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardactivationhistory',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about activation/deactivation'),
        ),
        migrations.AddField(
            model_name='cardactivationhistory',
            name='previous_tier',
            field=models.CharField(default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='cardbatchgeneration',
            name='batch_id',
            field=models.CharField(default='regular', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardbatchgeneration',
            name='distributed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardbatchgeneration',
            name='distributed_to',
            field=models.CharField(blank=True, help_text='Where cards were distributed', max_length=255),
        ),
        migrations.AddField(
            model_name='cardbatchgeneration',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cardbatchgeneration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('distributed', 'Distributed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='cardactivationhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_activation_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cardbatchgeneration',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_card_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cardactivationhistory',
            index=models.Index(fields=['user', 'activation_date'], name='card_activa_user_id_9712ca_idx'),
        ),
        migrations.AddIndex(
            model_name='cardactivationhistory',
            index=models.Index(fields=['card', 'activation_date'], name='card_activa_card_id_a65d85_idx'),
        ),
        migrations.AddIndex(
            model_name='cardbatchgeneration',
            index=models.Index(fields=['batch_id'], name='card_batch__batch_i_ff0f33_idx'),
        ),
        migrations.AddIndex(
            model_name='cardbatchgeneration',
            index=models.Index(fields=['tier', 'status'], name='card_batch__tier_5eb519_idx'),
        ),
        migrations.AddIndex(
            model_name='cardbatchgeneration',
            index=models.Index(fields=['generated_by', 'generated_date'], name='card_batch__generat_7a8d3d_idx'),
        ),
    ]
