# Generated by Django 5.2.6 on 2025-09-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_update_vip_card_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False, help_text='Whether MFA is enabled for this user'),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_required',
            field=models.BooleanField(default=False, help_text='Whether MFA is required (set automatically for VIP/Premium)'),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_setup_completed',
            field=models.BooleanField(default=False, help_text='Whether user has completed MFA setup'),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_setup_date',
            field=models.DateTimeField(blank=True, help_text='When MFA was first set up', null=True),
        ),
    ]
