# Generated by Django 5.2.6 on 2025-09-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_mfa_fields_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumdigitalcard',
            name='card_features',
            field=models.JSONField(default=dict, help_text='JSON object containing card-specific features'),
        ),
        migrations.AddField(
            model_name='premiumdigitalcard',
            name='encrypted_metadata',
            field=models.TextField(blank=True, help_text='Encrypted sensitive card data'),
        ),
    ]
