# Generated by Django 5.2.6 on 2025-09-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_premiumdigitalcard_card_features_and_more'),
    ]

    operations = [
    ]
