# Generated by Django 5.2.6 on 2025-09-12 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20250912_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('ride_booking', 'Ride Booking'), ('hotel_booking', 'Hotel Booking'), ('concierge_request', 'Concierge Request'), ('sos_activation', 'SOS Activation'), ('tier_upgrade', 'Tier Upgrade'), ('benefit_redemption', 'Benefit Redemption')], max_length=20)),
                ('event_description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location_data', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'card_usage_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='cardactivationhistory',
            options={'ordering': ['-attempted_at'], 'verbose_name': 'Card Activation History', 'verbose_name_plural': 'Card Activation History'},
        ),
        migrations.RemoveIndex(
            model_name='cardactivationhistory',
            name='card_activa_user_id_9712ca_idx',
        ),
        migrations.RemoveIndex(
            model_name='cardactivationhistory',
            name='card_activa_card_id_a65d85_idx',
        ),
        migrations.RenameField(
            model_name='cardactivationhistory',
            old_name='activation_date',
            new_name='attempted_at',
        ),
        migrations.RenameField(
            model_name='cardactivationhistory',
            old_name='client_ip',
            new_name='ip_address',
        ),
        migrations.RemoveField(
            model_name='cardactivationhistory',
            name='card',
        ),
        migrations.RemoveField(
            model_name='cardactivationhistory',
            name='new_tier',
        ),
        migrations.RemoveField(
            model_name='cardactivationhistory',
            name='previous_tier',
        ),
        migrations.AddField(
            model_name='cardactivationhistory',
            name='activation_code_used',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cardactivationhistory',
            name='activation_method',
            field=models.CharField(choices=[('mobile_app', 'Mobile App'), ('web_portal', 'Web Portal'), ('admin_panel', 'Admin Panel'), ('api_direct', 'Direct API')], default='mobile_app', max_length=20),
        ),
        migrations.AddField(
            model_name='cardactivationhistory',
            name='admin_user',
            field=models.ForeignKey(blank=True, help_text='Admin user who performed activation (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_card_activations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardactivationhistory',
            name='card_type',
            field=models.CharField(choices=[('vip', 'VIP Digital Card'), ('premium', 'Premium Digital Card')], default='vip', max_length=10),
        ),
        migrations.AddField(
            model_name='cardactivationhistory',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardactivationhistory',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error details if activation failed'),
        ),
        migrations.AddField(
            model_name='cardactivationhistory',
            name='premium_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activation_history', to='accounts.premiumdigitalcard'),
        ),
        migrations.AddField(
            model_name='cardactivationhistory',
            name='status',
            field=models.CharField(choices=[('success', 'Successful'), ('failed', 'Failed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='exit', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardactivationhistory',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cardactivationhistory',
            name='vip_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activation_history', to='accounts.vipdigitalcard'),
        ),
        migrations.AlterField(
            model_name='cardactivationhistory',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the activation'),
        ),
        migrations.AlterField(
            model_name='cardactivationhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_activation_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cardactivationhistory',
            index=models.Index(fields=['user', 'status'], name='card_activa_user_id_6fb19a_idx'),
        ),
        migrations.AddIndex(
            model_name='cardactivationhistory',
            index=models.Index(fields=['card_type', 'status'], name='card_activa_card_ty_bb49cd_idx'),
        ),
        migrations.AddIndex(
            model_name='cardactivationhistory',
            index=models.Index(fields=['attempted_at'], name='card_activa_attempt_285668_idx'),
        ),
        migrations.AddIndex(
            model_name='cardactivationhistory',
            index=models.Index(fields=['ip_address'], name='card_activa_ip_addr_610ed4_idx'),
        ),
        migrations.AddField(
            model_name='cardusagelog',
            name='premium_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='accounts.premiumdigitalcard'),
        ),
        migrations.AddField(
            model_name='cardusagelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardusagelog',
            name='vip_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='accounts.vipdigitalcard'),
        ),
        migrations.AddIndex(
            model_name='cardusagelog',
            index=models.Index(fields=['user', 'event_type'], name='card_usage__user_id_7446f3_idx'),
        ),
        migrations.AddIndex(
            model_name='cardusagelog',
            index=models.Index(fields=['timestamp'], name='card_usage__timesta_e064dd_idx'),
        ),
    ]
