# Generated by Django 5.2.6 on 2025-09-12 13:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_cardusagelog_alter_cardactivationhistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumCardBatchGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_id', models.CharField(max_length=50, unique=True)),
                ('tier', models.CharField(choices=[('vip', 'VIP'), ('vip_premium', 'VIP Premium')], max_length=15)),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_card', models.DecimalField(decimal_places=2, default=99.99, max_digits=10)),
                ('validity_months', models.PositiveIntegerField(default=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('distributed', 'Distributed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('distributed_to', models.CharField(blank=True, help_text='Where cards were distributed', max_length=255)),
                ('distributed_date', models.DateTimeField(blank=True, null=True)),
                ('distribution_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this batch')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_premium_card_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Premium Card Batch Generation',
                'verbose_name_plural': 'Premium Card Batch Generations',
                'db_table': 'premium_card_batch_generation',
                'ordering': ['-generated_date'],
                'indexes': [models.Index(fields=['batch_id'], name='premium_car_batch_i_f4fc5e_idx'), models.Index(fields=['tier', 'status'], name='premium_car_tier_7bb9e3_idx'), models.Index(fields=['generated_by', 'generated_date'], name='premium_car_generat_ec978d_idx')],
            },
        ),
    ]
