# Generated by Django 5.2.6 on 2025-09-12 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_premiumcardbatchgeneration'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumdigitalcard',
            name='batch_generation',
            field=models.ForeignKey(blank=True, help_text='Reference to batch generation if card was created in bulk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_cards', to='accounts.premiumcardbatchgeneration'),
        ),
    ]
