# Generated by Django 5.2.5 on 2025-08-06 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('center_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('center_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('radius_km', models.FloatField()),
                ('surge_multiplier', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('active_from', models.DateTimeField()),
                ('active_until', models.DateTimeField()),
                ('min_demand_ratio', models.FloatField(default=1.5, help_text='Demand/supply ratio to activate')),
                ('min_ride_requests', models.IntegerField(default=10, help_text='Minimum rides in timeframe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'surge_zones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RideMatchingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('search_radius_km', models.FloatField()),
                ('drivers_in_radius', models.IntegerField()),
                ('drivers_eligible', models.IntegerField()),
                ('drivers_contacted', models.IntegerField()),
                ('offers_created', models.IntegerField()),
                ('match_successful', models.BooleanField()),
                ('match_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('surge_multiplier', models.DecimalField(decimal_places=2, max_digits=4)),
                ('customer_tier', models.CharField(max_length=20)),
                ('ride_type', models.CharField(max_length=30)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.ride')),
                ('surge_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.surgezone')),
            ],
            options={
                'db_table': 'ride_matching_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ride'], name='ride_matchi_ride_id_89fcef_idx'), models.Index(fields=['timestamp'], name='ride_matchi_timesta_19f660_idx'), models.Index(fields=['match_successful', 'timestamp'], name='ride_matchi_match_s_cb7b95_idx')],
            },
        ),
    ]
