# Generated by Django 5.2.6 on 2025-09-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_ride_assigned_control_center_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationrecord',
            name='user_tier',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='ride',
            name='rider_tier',
            field=models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP'), ('vip_premium', 'VIP Premium')], default='normal', max_length=15),
        ),
    ]
