# Generated by Django 5.2.5 on 2025-08-06 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_loginattempt_mfatoken_securityevent_trusteddevice_and_more'),
        ('rides', '0002_surgezone_ridematchinglog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_vehicle_types', models.JSONField(default=list)),
                ('requires_non_smoking', models.BooleanField(default=False)),
                ('requires_air_conditioning', models.BooleanField(default=False)),
                ('max_waiting_time_minutes', models.IntegerField(default=10)),
                ('accepts_shared_rides', models.BooleanField(default=False)),
                ('price_sensitivity', models.CharField(choices=[('low', 'Price Sensitive'), ('medium', 'Balanced'), ('high', 'Service Priority')], default='medium', max_length=20)),
                ('requires_baby_seat', models.BooleanField(default=False)),
                ('requires_wheelchair_access', models.BooleanField(default=False)),
                ('has_pet', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked_drivers', models.ManyToManyField(blank=True, related_name='blocked_by_customers', to='accounts.driver')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ride_preferences', to=settings.AUTH_USER_MODEL)),
                ('preferred_drivers', models.ManyToManyField(blank=True, related_name='preferred_by_customers', to='accounts.driver')),
            ],
            options={
                'db_table': 'customer_preferences',
                'indexes': [models.Index(fields=['customer'], name='customer_pr_custome_5b98ce_idx'), models.Index(fields=['requires_baby_seat'], name='customer_pr_require_d05533_idx'), models.Index(fields=['requires_wheelchair_access'], name='customer_pr_require_14d00a_idx'), models.Index(fields=['updated_at'], name='customer_pr_updated_5155ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='DriverPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_pickup_areas', models.JSONField(default=list, help_text='List of preferred pickup area coordinates')),
                ('avoided_areas', models.JSONField(default=list, help_text='List of areas driver prefers to avoid')),
                ('max_pickup_distance_km', models.FloatField(default=15.0)),
                ('accepts_airport_rides', models.BooleanField(default=True)),
                ('accepts_long_distance', models.BooleanField(default=True)),
                ('accepts_night_rides', models.BooleanField(default=True)),
                ('min_ride_duration_minutes', models.IntegerField(default=5)),
                ('vip_customers_only', models.BooleanField(default=False)),
                ('familiar_customers_priority', models.BooleanField(default=True)),
                ('working_hours_start', models.TimeField(blank=True, null=True)),
                ('working_hours_end', models.TimeField(blank=True, null=True)),
                ('working_days', models.JSONField(default=list, help_text='List of working days (0=Monday, 6=Sunday)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matching_preferences', to='accounts.driver')),
            ],
            options={
                'db_table': 'driver_preferences',
                'indexes': [models.Index(fields=['driver'], name='driver_pref_driver__71a85a_idx'), models.Index(fields=['vip_customers_only'], name='driver_pref_vip_cus_cfe23a_idx'), models.Index(fields=['accepts_airport_rides'], name='driver_pref_accepts_d6137b_idx'), models.Index(fields=['updated_at'], name='driver_pref_updated_62bfda_idx')],
            },
        ),
    ]
