# Generated by Django 5.2.5 on 2025-08-11 23:50

import hotel_partnerships.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_partnerships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='pms_api_key',
            field=models.TextField(blank=True, help_text='Encrypted PMS API key'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='pms_webhook_secret',
            field=models.TextField(blank=True, help_text='Encrypted PMS webhook secret'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='preferred_vehicle_types',
            field=models.JSONField(default=list, help_text="List of preferred vehicle types: ['ECONOMY', 'COMFORT', 'LUXURY', 'VAN']", validators=[hotel_partnerships.models.validate_vehicle_types]),
        ),
    ]
