# Generated by Django 5.2.5 on 2025-08-12 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_center', '0001_initial'),
        ('fleet_management', '0001_initial'),
        ('rides', '0002_alter_ride_assigned_control_center_agent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emergencyincident',
            name='emergency_i_ride_id_de04b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='vipmonitoringsession',
            name='vip_monitor_ride_id_bf2ce5_idx',
        ),
        migrations.RemoveField(
            model_name='emergencyincident',
            name='ride_id',
        ),
        migrations.RemoveField(
            model_name='emergencyincident',
            name='vehicle_id',
        ),
        migrations.RemoveField(
            model_name='vipmonitoringsession',
            name='ride_id',
        ),
        migrations.RemoveField(
            model_name='vipmonitoringsession',
            name='vehicle_id',
        ),
        migrations.AddField(
            model_name='emergencyincident',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_incidents', to='rides.ride'),
        ),
        migrations.AddField(
            model_name='emergencyincident',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_incidents', to='fleet_management.vehicle'),
        ),
        migrations.AddField(
            model_name='vipmonitoringsession',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vip_monitoring_sessions', to='rides.ride'),
        ),
        migrations.AddField(
            model_name='vipmonitoringsession',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vip_monitoring_sessions', to='fleet_management.vehicle'),
        ),
        migrations.AddIndex(
            model_name='emergencyincident',
            index=models.Index(fields=['ride'], name='emergency_i_ride_id_de04b9_idx'),
        ),
        migrations.AddIndex(
            model_name='vipmonitoringsession',
            index=models.Index(fields=['ride'], name='vip_monitor_ride_id_bf2ce5_idx'),
        ),
    ]
