# Generated by Django 5.2.5 on 2025-08-06 13:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleLease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('auto_renewal', models.BooleanField(default=False)),
                ('renewal_period_months', models.PositiveIntegerField(default=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('revenue_share_model', models.CharField(choices=[('fixed_monthly', 'Fixed Monthly Payment'), ('percentage_revenue', 'Percentage of Revenue'), ('hybrid', 'Hybrid (Fixed + Percentage)'), ('per_ride', 'Per Ride Commission')], default='percentage_revenue', max_length=20)),
                ('fixed_monthly_payment', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed monthly lease payment to vehicle owner', max_digits=10)),
                ('revenue_share_percentage', models.DecimalField(decimal_places=2, default=25.0, help_text='Percentage of ride revenue shared with vehicle owner', max_digits=5)),
                ('per_ride_commission', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed commission per completed ride', max_digits=8)),
                ('minimum_monthly_guarantee', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum guaranteed monthly payment to owner', max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('maximum_daily_hours', models.PositiveIntegerField(default=12, help_text='Maximum operating hours per day')),
                ('maximum_monthly_mileage', models.PositiveIntegerField(default=5000, help_text='Maximum mileage per month')),
                ('allowed_service_areas', models.TextField(help_text='Comma-separated list of allowed service areas')),
                ('maintenance_responsibility', models.CharField(choices=[('owner', 'Vehicle Owner'), ('fleet', 'Fleet Company'), ('shared', 'Shared Responsibility')], default='fleet', max_length=10)),
                ('insurance_responsibility', models.CharField(choices=[('owner', 'Vehicle Owner'), ('fleet', 'Fleet Company'), ('shared', 'Shared Responsibility')], default='fleet', max_length=10)),
                ('fuel_responsibility', models.CharField(choices=[('owner', 'Vehicle Owner'), ('fleet', 'Fleet Company'), ('shared', 'Shared Responsibility')], default='fleet', max_length=10)),
                ('total_rides_completed', models.PositiveIntegerField(default=0)),
                ('total_revenue_generated', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_owner_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_fleet_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('average_daily_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_mileage', models.PositiveIntegerField(default=0)),
                ('current_mileage', models.PositiveIntegerField(default=0)),
                ('excess_mileage_rate', models.DecimalField(decimal_places=2, default=0.5, help_text='Rate per km for excess mileage', max_digits=6)),
                ('contract_document', models.FileField(upload_to='contracts/')),
                ('vehicle_handover_checklist', models.FileField(blank=True, null=True, upload_to='contracts/handover/')),
                ('signed_date', models.DateTimeField(blank=True, null=True)),
                ('owner_signature', models.ImageField(blank=True, null=True, upload_to='contracts/signatures/')),
                ('fleet_signature', models.ImageField(blank=True, null=True, upload_to='contracts/signatures/')),
                ('termination_notice_period_days', models.PositiveIntegerField(default=30)),
                ('early_termination_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('termination_date', models.DateTimeField(blank=True, null=True)),
                ('termination_reason', models.TextField(blank=True)),
                ('data_sharing_consent', models.BooleanField(default=False)),
                ('data_sharing_consent_date', models.DateTimeField(blank=True, null=True)),
                ('performance_data_retention_days', models.PositiveIntegerField(default=2555)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fleet_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_contracts', to='fleet_management.fleetcompany')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_contracts', to='fleet_management.vehicle')),
                ('vehicle_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_contracts_as_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vehicle_leases',
            },
        ),
        migrations.CreateModel(
            name='LeasePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_period_start', models.DateField()),
                ('payment_period_end', models.DateField()),
                ('base_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('revenue_share_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('excess_mileage_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('maintenance_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('damage_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rides_completed', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_mileage', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='vehicle_leasing.vehiclelease')),
            ],
            options={
                'db_table': 'lease_payments',
            },
        ),
        migrations.AddIndex(
            model_name='vehiclelease',
            index=models.Index(fields=['vehicle_owner'], name='vehicle_lea_vehicle_a425bd_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelease',
            index=models.Index(fields=['fleet_company'], name='vehicle_lea_fleet_c_9f01d4_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelease',
            index=models.Index(fields=['vehicle'], name='vehicle_lea_vehicle_d53a7c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelease',
            index=models.Index(fields=['status'], name='vehicle_lea_status_a67a5a_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelease',
            index=models.Index(fields=['start_date', 'end_date'], name='vehicle_lea_start_d_54a9a3_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelease',
            index=models.Index(fields=['revenue_share_model'], name='vehicle_lea_revenue_adffcd_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelease',
            index=models.Index(fields=['created_at'], name='vehicle_lea_created_9387b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclelease',
            unique_together={('vehicle', 'fleet_company', 'start_date')},
        ),
        migrations.AddIndex(
            model_name='leasepayment',
            index=models.Index(fields=['lease'], name='lease_payme_lease_i_591636_idx'),
        ),
        migrations.AddIndex(
            model_name='leasepayment',
            index=models.Index(fields=['payment_period_start', 'payment_period_end'], name='lease_payme_payment_1e7fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='leasepayment',
            index=models.Index(fields=['status'], name='lease_payme_status_13049a_idx'),
        ),
        migrations.AddIndex(
            model_name='leasepayment',
            index=models.Index(fields=['payment_date'], name='lease_payme_payment_be0787_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leasepayment',
            unique_together={('lease', 'payment_period_start', 'payment_period_end')},
        ),
    ]
