# Generated by Django 5.2.5 on 2025-08-12 02:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_leasing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelease',
            name='revenue_share_percentage',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='Percentage of ride revenue shared with vehicle owner', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
