# Generated by Django 5.2.5 on 2025-08-12 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_tracking', '0002_bufferedlocation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bufferedlocation',
            new_name='buffered_lo_buffer__fec78f_idx',
            old_name='gps_buffer_idx',
        ),
        migrations.RenameIndex(
            model_name='bufferedlocation',
            new_name='buffered_lo_timesta_485c73_idx',
            old_name='gps_timestamp_idx',
        ),
        migrations.AlterField(
            model_name='offlinegpsbuffer',
            name='buffered_locations',
            field=models.JSONField(default=list, help_text='Array of GPS locations recorded offline (legacy)'),
        ),
    ]
